# Generated by Django 4.2.16 on 2026-04-05 15:57

import apps.api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_6', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('file', models.FileField(upload_to=apps.api.models.invoice_upload_to)),
                ('verify_status', models.CharField(choices=[('pending', '待验真'), ('success', '验真成功'), ('failed', '验真失败')], default='pending', max_length=20)),
                ('verify_msg', models.CharField(blank=True, max_length=255)),
                ('invoice_code', models.CharField(blank=True, max_length=32)),
                ('invoice_num', models.CharField(blank=True, max_length=32)),
                ('invoice_date', models.CharField(blank=True, max_length=20)),
                ('check_code', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=100)),
                ('seller_name', models.CharField(blank=True, max_length=100)),
                ('ocr_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.employee')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('expense_type', models.CharField(max_length=50)),
                ('reimbursement_date', models.DateField()),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_upper', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='api.employee')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement', to='api.invoice')),
            ],
            options={
                'db_table': 'reimbursement',
            },
        ),
    ]
