from django.urls import path
from .views import (
    AccountantReimbursementAuditView,
    AccountantReimbursementHistoryListView,
    AccountantReimbursementPendingListView,
    DashboardStatsView,
    EmployeeLookupView,
    LoginView,
    MyReimbursementHistoryView,
    OcrByCodeView,
    ProfileView,
    ProjectBudgetTemplateView,
    ReimbursementStatisticsView,
    RegisterView,
    ReimbursementEditDeleteRevokeView,
    ReimbursementDraftOrSubmitView,
    TemporaryLoanDraftOrSubmitView,
    UploadAndVerifyInvoiceView,
    VerifySuccessInvoiceListView,
)

urlpatterns = [
    path('auth/register/', RegisterView.as_view()),
    path('auth/login/', LoginView.as_view()),
    path('auth/profile/', ProfileView.as_view()),
    path('auth/employee-by-no/', EmployeeLookupView.as_view()),
    path('invoice/upload-verify/', UploadAndVerifyInvoiceView.as_view()),
    path('invoice/ocr-by-code/', OcrByCodeView.as_view()),
    path('reimbursement/save/', ReimbursementDraftOrSubmitView.as_view()),
    path('loan/save/', TemporaryLoanDraftOrSubmitView.as_view()),
    path('reimbursement/history/', MyReimbursementHistoryView.as_view()),
    path('reimbursement/<int:reimbursement_id>/manage/', ReimbursementEditDeleteRevokeView.as_view()),
    path('accountant/reimbursement/pending/', AccountantReimbursementPendingListView.as_view()),
    path('accountant/reimbursement/history/', AccountantReimbursementHistoryListView.as_view()),
    path('accountant/reimbursement/<int:reimbursement_id>/audit/', AccountantReimbursementAuditView.as_view()),
    path('dashboard/stats/', DashboardStatsView.as_view()),
    path('invoice/success-list/', VerifySuccessInvoiceListView.as_view()),
    path('budget/template/', ProjectBudgetTemplateView.as_view()),
    path('stats/reimbursement/', ReimbursementStatisticsView.as_view()),
]
